### ISSUE TITLE
Contact login logout sounds

### ISSUE THREAD

**Issue by GrayHatter** [zamaudio/toxsounds#1]
These should be as LEAST intrusive as possible. It should be very easy for the user to tune them out, for when they don't care if they have a friend coming or going. But still unique enough that if they are waiting for a friend, they can pick the sound out from minor environmental noise (clicking, typing, maybe a movie on their phone).

**Comment by zamaudio** [comment]
Fixed.  Please review.

**Comment by GrayHatter** [comment]
I like em! I'm going to leave this open for a bit for others to comment on them.

@tsudoko
