### ISSUE TITLE
Needs a call dropped sound

### ISSUE THREAD

**Issue by GrayHatter** [zamaudio/toxsounds#10]

**Comment by zamaudio** [comment]
Copied from endcall

**Comment by GrayHatter** [comment]
can you make it more musical? just the smallest bit closer to the ringtones

**Comment by zamaudio** [comment]
How can I make the sound of a handset hitting the reciever more musical?

**Comment by GrayHatter** [comment]
lengthen, add reverb, autotune,

**Comment by GrayHatter** [comment]
may need to mess with that order
