### ISSUE TITLE
Incoming Ringtone

### ISSUE THREAD

**Issue by GrayHatter** [zamaudio/toxsounds#2]
This one should be intrusive, if a friend is calling they need the users attention. Idealy it would sound similar to a ringtone (see https://xkcd.com/479/ ). But it should NOT be a simple frequency shift.

Because this is part of the core purpose of the app it should try to match the idea of security, privacy, and openness... That's right, I'm asking for you to represent the tox core values with a ringtone... Yes I am insane, why do you ask?

**Comment by zamaudio** [comment]
Okay, I made a new attempt.  Is it better?

**Comment by GrayHatter** [comment]
yeah, that's better, I like the dropoffs, but is feels a little slow and
musical, I also think it needs to be either deeper to match the login/out
or higher to separate it from them

**Comment by zamaudio** [comment]
Okay, I did a slightly faster one
