### ISSUE TITLE
Outgoing ringtone

### ISSUE THREAD

**Issue by GrayHatter** [zamaudio/toxsounds#3]
We know we're calling them, it doesn't need to be flashy or impressive. But it will need to be as calming as possible. If the user hears it for too long, that means they want to talk to their friend, but s/he isn't answering that'll be annoying enough, tox shouldn't add to that! Soft and gentle!

**Comment by zamaudio** [comment]
I think the outgoing ringtone should be the same as the incoming one, so that people easily recognise it as the calling tone.

**Comment by GrayHatter** [comment]
fair enough
