### ISSUE TITLE
Needs Incoming text message sound

### ISSUE THREAD

**Issue by GrayHatter** [zamaudio/toxsounds#4]
Short, soft tones and low pitched. Higher pitches are more likely to wake someone up from sleep, and in keeping with every other issue, I'm going for NOT ANNOYING. The quickest way to get me to uninstall your app, is if you wake me up with it.

**Comment by zamaudio** [comment]
Added

**Comment by zamaudio** [comment]
Updated

**Comment by GrayHatter** [comment]
perfect!
