### ISSUE TITLE
Incoming file transfers.

### ISSUE THREAD

**Issue by GrayHatter** [zamaudio/toxsounds#5]
Similar to messages, Short and soft. These should also be a little more interrupting as we're probably waiting for them, and are unlikely to be spammed to us.

**Comment by zamaudio** [comment]
Made a soft "ding"

**Comment by zamaudio** [comment]
Updated

**Comment by GrayHatter** [comment]
sounds too much like a heart beat

**Comment by GrayHatter** [comment]
reverse the notes?

**Comment by zamaudio** [comment]
Done

**Comment by GrayHatter** [comment]
can you bump the gain? I can barely hear it?

**Comment by zamaudio** [comment]
Done

**Comment by GrayHatter** [comment]
it's good thanks!
