### ISSUE TITLE
Incoming video call

### ISSUE THREAD

**Issue by GrayHatter** [zamaudio/toxsounds#8]
Should be very different from ringtones, I'd like the user to know by the first/second note if they need to go find some pants...

**Comment by zamaudio** [comment]
HAHA good idea... updated

**Comment by GrayHatter** [comment]
I really like this version, a lot more than the generic ringtone. Can you upload a version without the very first pipe tone? I'm not sure if that's the best note to start with.

**Comment by zamaudio** [comment]
Removed first tone

**Comment by GrayHatter** [comment]
I like it!
